name: quicklogic
channels:
  - conda-forge
  - litex-hub
dependencies:
  - litex-hub::yosys=0.9_5266_g0fb4224e=20210301_104249_py37
  - litex-hub::symbiflow-yosys-plugins=1.0.0_7_338_g93157fb=20210507_125510
  - litex-hub::vtr-optimized=8.0.0_3614_gb3b34e77a=20210507_125510
  # TODO: remove when quicklogic-vtr will be updated to version built after https://github.com/hdl/conda-eda/pull/90
  # or when conda-forge will rename API breaking tbb to another name (see https://github.com/conda-forge/tbb-feedstock/issues/81)
  - tbb
  - python=3.7  
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:../common/requirements.txt
    - -r file:requirements.txt
