name: quicklogic
channels:
  - conda-forge
  - litex-hub
dependencies:
  - litex-hub::quicklogic-yosys=v0.8.0_45_gcb3eef2b=20201216_065815
  - litex-hub::quicklogic-yosys-plugins=v1.2.0_11_g21045a9=20201216_065815
  - litex-hub::quicklogic-vtr=v8.0.0.rc2_4003_g8980e4621=20200902_114536
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:../common/requirements.txt
    - -r file:requirements.txt
