language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

install: pip install yapf

script:
  - make format
  - test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }
  - source .github/travis/check_license.sh
  - source .github/travis/check_python_scripts.sh

notifications:
  email: false
