name: symbiflow-env
channels:
  - defaults
  - symbiflow
dependencies:
  - symbiflow-yosys=0.8_6021_gd8b2d1a2=20200708_083630
  - symbiflow-yosys-plugins=1.0.0.7_0159_g4243dae=20201002_094407
  - symbiflow-vtr=8.0.0.rc2_5097_gf1a3bcc2a=20200916_072439
  - prjxray-tools
  - prjxray-db
  - pip
  - pip:                            # Packages installed from PyPI
    - -r file:../common/requirements.txt
    - -r file:requirements.txt
